const { chromium } = require('@playwright/test');
const path = require('path');
const fs = require('fs');
const { execSync } = require('child_process');

(async () => {
  console.log("Starting Playwright recording...");
  const browser = await chromium.launch({
    executablePath: "/usr/bin/google-chrome",
    args: ['--no-sandbox', '--disable-setuid-sandbox']
  });
  
  const context = await browser.newContext({
    viewport: { width: 1280, height: 720 },
    recordVideo: {
      dir: path.join(__dirname),
      size: { width: 1280, height: 720 }
    }
  });

  const page = await context.newPage();
  const fileUrl = `file://${path.join(__dirname, 'presentation.html')}`;
  console.log(`Navigating to ${fileUrl}...`);
  await page.goto(fileUrl);
  
  // The presentation runs 4 slides * 8 seconds = 32 seconds.
  // Wait 35 seconds to capture all transitions.
  console.log("Recording presentation for 35 seconds...");
  await page.waitForTimeout(35000);

  console.log("Closing browser...");
  await context.close();
  await browser.close();

  // Find the generated video file (Playwright records in .webm format)
  const files = fs.readdirSync(__dirname);
  const webmFile = files.find(f => f.endsWith('.webm'));
  
  if (webmFile) {
    const webmPath = path.join(__dirname, webmFile);
    const mp4Path = path.join(__dirname, 'system_overview.mp4');
    console.log(`WebM video generated at: ${webmPath}`);
    
    // Convert WebM to MP4 using ffmpeg
    console.log("Converting WebM to MP4...");
    try {
      execSync(`ffmpeg -y -i "${webmPath}" -c:v libx264 -pix_fmt yuv420p "${mp4Path}"`, { stdio: 'inherit' });
      console.log(`MP4 video successfully created at: ${mp4Path}`);
      
      // Clean up the temporary WebM file
      fs.unlinkSync(webmPath);
      console.log("Temporary WebM file removed.");
    } catch (err) {
      console.error("Error converting video using ffmpeg:", err);
    }
  } else {
    console.error("Error: No video file was generated by Playwright.");
  }
})();
