export type EntityType = "Employee" | "Vehicle" | "Equipment";
export type AccessStatus =
  | "Granted"
  | "Denied"
  | "Expired Credential"
  | "Tailgate Alert";
export type AccessMethod =
  | "QR Scan"
  | "Mobile QR"
  | "Kiosk Scan"
  | "Reader Tap";

export interface AccessLogEntry {
  id: string;
  timestamp: string;
  entityName: string;
  entityType: EntityType;
  qrCodeId: string;
  zone: string;
  accessMethod: AccessMethod;
  status: AccessStatus;
  duration: number;
  operator: string;
  deviceId: string;
  notes?: string;
  latitude?: string;
  longitude?: string;
}

export const ALL_ZONES = [
  "Server Room B",
  "Loading Bay 2",
  "R&D Lab",
  "Warehouse A",
  "Executive Floor",
  "Gate A",
  "Data Center",
  "Yard East",
  "Parking Zone C",
  "Lobby Main",
  "Roof Access",
  "Chemical Storage",
];

export const accessLogsData: AccessLogEntry[] = [
  {
    id: "log-001",
    timestamp: "2026-05-18T23:38:14",
    entityName: "Priya Krishnamurthy",
    entityType: "Employee",
    qrCodeId: "QR-EMP-4821",
    zone: "Server Room B",
    accessMethod: "QR Scan",
    status: "Granted",
    duration: 3,
    operator: "Reader-SRB-01",
    deviceId: "DEV-0041",
  },
  {
    id: "log-002",
    timestamp: "2026-05-18T23:35:52",
    entityName: "Truck TK-7741",
    entityType: "Vehicle",
    qrCodeId: "QR-VEH-0293",
    zone: "Loading Bay 2",
    accessMethod: "Kiosk Scan",
    status: "Granted",
    duration: 2,
    operator: "Kiosk-LB-02",
    deviceId: "DEV-0012",
  },
  {
    id: "log-003",
    timestamp: "2026-05-18T23:31:07",
    entityName: "Carlos Mendes",
    entityType: "Employee",
    qrCodeId: "QR-EMP-1193",
    zone: "R&D Lab",
    accessMethod: "Mobile QR",
    status: "Denied",
    duration: 1,
    operator: "Reader-RD-01",
    deviceId: "DEV-0033",
    notes: "Insufficient clearance level for R&D zone",
  },
  {
    id: "log-004",
    timestamp: "2026-05-18T23:28:41",
    entityName: "Forklift FL-04",
    entityType: "Equipment",
    qrCodeId: "QR-EQP-0872",
    zone: "Warehouse A",
    accessMethod: "Reader Tap",
    status: "Granted",
    duration: 4,
    operator: "Reader-WH-A3",
    deviceId: "DEV-0027",
  },
  {
    id: "log-005",
    timestamp: "2026-05-18T23:22:19",
    entityName: "Amara Osei",
    entityType: "Employee",
    qrCodeId: "QR-EMP-3310",
    zone: "Executive Floor",
    accessMethod: "QR Scan",
    status: "Expired Credential",
    duration: 1,
    operator: "Reader-EX-01",
    deviceId: "DEV-0008",
    notes: "QR code expired 2026-05-11 — immediate revocation required",
  },
  {
    id: "log-006",
    timestamp: "2026-05-18T23:17:33",
    entityName: "Van VN-2284",
    entityType: "Vehicle",
    qrCodeId: "QR-VEH-1104",
    zone: "Gate A",
    accessMethod: "Kiosk Scan",
    status: "Tailgate Alert",
    duration: 0,
    operator: "Kiosk-GA-01",
    deviceId: "DEV-0003",
    notes: "Tailgate detected — secondary vehicle followed without scan",
  },
  {
    id: "log-007",
    timestamp: "2026-05-18T23:09:54",
    entityName: "Lena Hoffmann",
    entityType: "Employee",
    qrCodeId: "QR-EMP-2255",
    zone: "Data Center",
    accessMethod: "QR Scan",
    status: "Granted",
    duration: 3,
    operator: "Reader-DC-02",
    deviceId: "DEV-0055",
  },
  {
    id: "log-008",
    timestamp: "2026-05-18T22:58:12",
    entityName: "Crane CR-01",
    entityType: "Equipment",
    qrCodeId: "QR-EQP-0031",
    zone: "Yard East",
    accessMethod: "Reader Tap",
    status: "Granted",
    duration: 2,
    operator: "Reader-YE-01",
    deviceId: "DEV-0018",
  },
  {
    id: "log-009",
    timestamp: "2026-05-18T22:47:38",
    entityName: "David Nakamura",
    entityType: "Employee",
    qrCodeId: "QR-EMP-0447",
    zone: "Lobby Main",
    accessMethod: "Mobile QR",
    status: "Granted",
    duration: 2,
    operator: "Reader-LB-01",
    deviceId: "DEV-0002",
  },
  {
    id: "log-010",
    timestamp: "2026-05-18T22:41:03",
    entityName: "Sedan SD-1192",
    entityType: "Vehicle",
    qrCodeId: "QR-VEH-0881",
    zone: "Parking Zone C",
    accessMethod: "Kiosk Scan",
    status: "Denied",
    duration: 1,
    operator: "Kiosk-PZ-C1",
    deviceId: "DEV-0044",
    notes: "Zone restricted during security audit window",
  },
  {
    id: "log-011",
    timestamp: "2026-05-18T22:33:57",
    entityName: "Scanner SC-18",
    entityType: "Equipment",
    qrCodeId: "QR-EQP-1188",
    zone: "R&D Lab",
    accessMethod: "Reader Tap",
    status: "Granted",
    duration: 3,
    operator: "Reader-RD-02",
    deviceId: "DEV-0039",
  },
  {
    id: "log-012",
    timestamp: "2026-05-18T22:25:14",
    entityName: "Fatima Al-Rashid",
    entityType: "Employee",
    qrCodeId: "QR-EMP-0912",
    zone: "Chemical Storage",
    accessMethod: "QR Scan",
    status: "Granted",
    duration: 4,
    operator: "Reader-CS-01",
    deviceId: "DEV-0061",
  },
  {
    id: "log-013",
    timestamp: "2026-05-18T22:17:29",
    entityName: "Truck TK-5530",
    entityType: "Vehicle",
    qrCodeId: "QR-VEH-2271",
    zone: "Gate A",
    accessMethod: "Kiosk Scan",
    status: "Expired Credential",
    duration: 1,
    operator: "Kiosk-GA-01",
    deviceId: "DEV-0003",
    notes: "Vehicle registration QR expired 2026-05-15",
  },
  {
    id: "log-014",
    timestamp: "2026-05-18T22:09:41",
    entityName: "Yuki Tanaka",
    entityType: "Employee",
    qrCodeId: "QR-EMP-1872",
    zone: "Server Room B",
    accessMethod: "QR Scan",
    status: "Granted",
    duration: 2,
    operator: "Reader-SRB-01",
    deviceId: "DEV-0041",
  },
  {
    id: "log-015",
    timestamp: "2026-05-18T22:01:08",
    entityName: "Pallet Jack PJ-07",
    entityType: "Equipment",
    qrCodeId: "QR-EQP-0714",
    zone: "Warehouse A",
    accessMethod: "Reader Tap",
    status: "Granted",
    duration: 2,
    operator: "Reader-WH-A1",
    deviceId: "DEV-0025",
  },
  {
    id: "log-016",
    timestamp: "2026-05-18T21:54:33",
    entityName: "Jerome Baptiste",
    entityType: "Employee",
    qrCodeId: "QR-EMP-3041",
    zone: "Roof Access",
    accessMethod: "Mobile QR",
    status: "Denied",
    duration: 1,
    operator: "Reader-RF-01",
    deviceId: "DEV-0070",
    notes: "Roof access requires Tier-3 clearance — employee is Tier-2",
  },
  {
    id: "log-017",
    timestamp: "2026-05-18T21:46:17",
    entityName: "Minibus MB-0443",
    entityType: "Vehicle",
    qrCodeId: "QR-VEH-0443",
    zone: "Parking Zone C",
    accessMethod: "Kiosk Scan",
    status: "Granted",
    duration: 2,
    operator: "Kiosk-PZ-C1",
    deviceId: "DEV-0044",
  },
  {
    id: "log-018",
    timestamp: "2026-05-18T21:38:52",
    entityName: "Sonia Petrov",
    entityType: "Employee",
    qrCodeId: "QR-EMP-2918",
    zone: "Data Center",
    accessMethod: "QR Scan",
    status: "Granted",
    duration: 3,
    operator: "Reader-DC-01",
    deviceId: "DEV-0054",
  },
  {
    id: "log-019",
    timestamp: "2026-05-18T21:30:04",
    entityName: "Compressor CP-03",
    entityType: "Equipment",
    qrCodeId: "QR-EQP-0033",
    zone: "Yard East",
    accessMethod: "Reader Tap",
    status: "Tailgate Alert",
    duration: 0,
    operator: "Reader-YE-02",
    deviceId: "DEV-0019",
    notes:
      "Unauthorized equipment followed through gate without individual scan",
  },
  {
    id: "log-020",
    timestamp: "2026-05-18T21:22:16",
    entityName: "Hassan Al-Farsi",
    entityType: "Employee",
    qrCodeId: "QR-EMP-4102",
    zone: "Executive Floor",
    accessMethod: "QR Scan",
    status: "Granted",
    duration: 2,
    operator: "Reader-EX-02",
    deviceId: "DEV-0009",
  },
  {
    id: "log-021",
    timestamp: "2026-05-18T21:14:39",
    entityName: "Truck TK-8812",
    entityType: "Vehicle",
    qrCodeId: "QR-VEH-3381",
    zone: "Loading Bay 2",
    accessMethod: "Kiosk Scan",
    status: "Granted",
    duration: 3,
    operator: "Kiosk-LB-01",
    deviceId: "DEV-0011",
  },
  {
    id: "log-022",
    timestamp: "2026-05-18T21:06:28",
    entityName: "Ingrid Larsen",
    entityType: "Employee",
    qrCodeId: "QR-EMP-1544",
    zone: "Lobby Main",
    accessMethod: "Mobile QR",
    status: "Granted",
    duration: 2,
    operator: "Reader-LB-01",
    deviceId: "DEV-0002",
  },
  {
    id: "log-023",
    timestamp: "2026-05-18T20:58:45",
    entityName: "Welder WD-11",
    entityType: "Equipment",
    qrCodeId: "QR-EQP-1011",
    zone: "Warehouse A",
    accessMethod: "Reader Tap",
    status: "Expired Credential",
    duration: 1,
    operator: "Reader-WH-A2",
    deviceId: "DEV-0026",
    notes: "Equipment QR maintenance cycle expired — requires recertification",
  },
  {
    id: "log-024",
    timestamp: "2026-05-18T20:51:03",
    entityName: "Kwame Asante",
    entityType: "Employee",
    qrCodeId: "QR-EMP-0773",
    zone: "Chemical Storage",
    accessMethod: "QR Scan",
    status: "Denied",
    duration: 1,
    operator: "Reader-CS-01",
    deviceId: "DEV-0061",
    notes: "Hazmat certification not on file — access blocked",
  },
];
