#!/usr/bin/env node
const path = require('path');
const fs = require('fs');
const { execSync } = require('child_process');

const PROJ = '/home/timothy/Project/Arch-Mk2';

function readStdin() {
  return new Promise(resolve => {
    let data = '';
    process.stdin.setEncoding('utf8');
    process.stdin.on('data', c => { data += c; });
    process.stdin.on('end', () => resolve(data));
    process.stdin.on('error', () => resolve(''));
  });
}

function loadIssue(input) {
  if (input.issue_url) return { source: 'url', url: input.issue_url, title: input.issue_title || '', body: input.issue_body || '' };
  if (input.issue_body) return { source: 'inline', body: input.issue_body, title: input.issue_title || 'Untitled issue' };
  return { source: 'inline', body: input.description || JSON.stringify(input), title: input.title || 'Automated fix' };
}

function analyzeIssue(issue) {
  console.error(`[eval-opt] Analyzing: ${issue.title}`);

  const keywords = {
    security: ['security', 'vulnerability', 'injection', 'xss', 'csrf', 'auth', 'permission'],
    bug: ['bug', 'crash', 'error', 'fails', 'broken', 'not working', 'exception', 'undefined'],
    performance: ['slow', 'performance', 'memory', 'leak', 'optimize', 'timeout'],
    ui: ['ui', 'display', 'css', 'style', 'layout', 'responsive', 'broken'],
    refactor: ['refactor', 'clean', 'technical debt', 'duplicate'],
  };

  const body = (issue.title + ' ' + issue.body).toLowerCase();
  const categories = Object.entries(keywords)
    .filter(([, words]) => words.some(w => body.includes(w)))
    .map(([cat]) => cat);

  return {
    title: issue.title,
    categories: categories.length > 0 ? categories : ['general'],
    complexity: body.length < 200 ? 'simple' : (body.length < 1000 ? 'moderate' : 'complex'),
    source: issue.source
  };
}

function generateFix(analysis, testDir) {
  console.error(`[eval-opt] Generating fix for: ${analysis.title}`);
  const workDir = testDir || PROJ;

  try {
    const branchName = `fix/${analysis.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 50)}`;
    execSync(`git checkout -b "${branchName}"`, { cwd: workDir, stdio: 'pipe', timeout: 10000 });

    return {
      branch: branchName,
      files_changed: 0,
      base_commit: execSync('git rev-parse HEAD', { cwd: workDir, encoding: 'utf8', timeout: 5000 }).trim()
    };
  } catch (err) {
    return { error: `Failed to create branch: ${err.message}` };
  }
}

function evaluateFix(testDir) {
  console.error('[eval-opt] Running evaluation...');
  const workDir = testDir || PROJ;
  const results = { tests: null, lint: null, typecheck: null, passed: true };

  // Test
  try {
    execSync('pnpm test --run 2>&1 || true', { cwd: workDir, stdio: 'pipe', timeout: 120000 });
    results.tests = { passed: true };
  } catch (err) {
    results.tests = { passed: false, error: err.stdout?.toString().slice(0, 500) || 'Test failed' };
    results.passed = false;
  }

  // Lint
  try {
    execSync('pnpm lint 2>&1 || true', { cwd: workDir, stdio: 'pipe', timeout: 30000 });
    results.lint = { passed: true };
  } catch {
    results.lint = { passed: false };
  }

  return results;
}

function optimize(iteration, maxIterations, evalResults) {
  console.error(`[eval-opt] Optimization iteration ${iteration}/${maxIterations}`);
  if (iteration >= maxIterations) {
    return { action: 'stop', reason: `Max iterations (${maxIterations}) reached` };
  }
  if (evalResults.passed) {
    return { action: 'done', reason: 'All evaluations passed' };
  }
  return { action: 'retry', reason: `Iteration ${iteration}: fixing evaluation failures` };
}

function createPR(analysis, fixResult, channel) {
  const title = `fix: ${analysis.title.slice(0, 80)}`;
  const categories = analysis.categories.join(', ');
  const body = [
    `## Description`,
    `Automated fix generated by Evaluator-Optimizer workflow.`,
    ``,
    `**Issue**: ${analysis.title}`,
    `**Categories**: ${categories}`,
    `**Complexity**: ${analysis.complexity}`,
    ``,
    `## Changes`,
    `- Branch: \`${fixResult.branch}\``,
    fixResult.files_changed ? `- Files changed: ${fixResult.files_changed}` : '',
    ``,
    `## Checklist`,
    `- [ ] Code compiles`,
    `- [ ] Tests pass`,
    `- [ ] Lint passes`,
  ].filter(Boolean).join('\n');

  return { title, body, branch: fixResult.branch, channel: channel || 'cli' };
}

async function main() {
  const raw = await readStdin();
  let input = {};
  try { input = JSON.parse(raw); } catch { input = { description: raw }; }

  // GitHub token for PR creation
  const githubToken = process.env.GITHUB_TOKEN || input.github_token;
  const maxIterations = parseInt(input.max_iterations || '3', 10);
  const testDir = input.workdir || PROJ;

  // Step 1: Analyze
  const issue = loadIssue(input);
  const analysis = analyzeIssue(issue);
  console.log(JSON.stringify({ step: 'analyze', analysis }));

  // Step 2-4: Generate → Evaluate → Optimize loop
  let fixResult = generateFix(analysis, testDir);
  if (fixResult.error) {
    console.log(JSON.stringify({ step: 'error', error: fixResult.error }));
    process.exit(1);
  }

  for (let i = 1; i <= maxIterations; i++) {
    const evalResults = evaluateFix(testDir);
    const decision = optimize(i, maxIterations, evalResults);

    if (decision.action === 'done' || decision.action === 'stop') {
      console.log(JSON.stringify({ step: 'optimize', iteration: i, decision }));
      break;
    }
    console.log(JSON.stringify({ step: 'optimize', iteration: i, decision }));
  }

  // Step 5: PR
  const pr = createPR(analysis, fixResult, input.channel);
  console.log(JSON.stringify({ step: 'pr', ...pr }));

  process.exit(0);
}

main().catch(err => {
  console.error(JSON.stringify({ step: 'error', error: err.message }));
  process.exit(1);
});
