/**
 * generated.ts — AUTO-GENERATED. DO NOT EDIT.
 *
 * Generated by: packages/theme/scripts/generate-tokens.mjs
 * Source:       packages/theme/src/css/variables.css
 *
 * Re-run with: node packages/theme/scripts/generate-tokens.mjs
 * Or via Turbo: pnpm --filter @repo/theme codegen
 *
 * This file provides typed `var(--token)` references for use in:
 * - Framer Motion style props
 * - Canvas/WebGL drawing
 * - Runtime style injection
 *
 * For static Tailwind usage, use the className utilities instead
 * (e.g. `text-[var(--text-heading)]` or `shadow-card`).
 */

export const tokens = {
  color: {
    bg: {
      primary: "var(--bg-primary)",
      secondary: "var(--bg-secondary)",
      tertiary: "var(--bg-tertiary)",
    },
    border: {
      subtle: "var(--border-subtle)",
      default: "var(--border-default)",
      emphasis: "var(--border-emphasis)",
    },
    text: {
      muted: "var(--text-muted)",
      secondary: "var(--text-secondary)",
      body: "var(--text-body)",
      primary: "var(--text-primary)",
      heading: "var(--text-heading)",
      onGlass: "var(--text-on-glass)",
      onGlassMuted: "var(--text-on-glass-muted)",
    },
    accent: {
      red: "var(--accent-red)",
      orange: "var(--accent-orange)",
      green: "var(--accent-green)",
      blue: "var(--accent-blue)",
      cyan: "var(--accent-cyan)",
      indigo: "var(--accent-indigo)",
      violet: "var(--accent-violet)",
      alert: "var(--accent-alert)",
      amber: "var(--accent-amber)",
      emerald: "var(--accent-emerald)",
      foreground: "var(--accent-foreground)",
    },
    mac: {
      red: "var(--mac-red)",
      yellow: "var(--mac-yellow)",
      green: "var(--mac-green)",
      menuBarHeight: "var(--mac-menu-bar-height)",
    },
    glass: {
      surface: "var(--glass-surface)",
      surfaceHover: "var(--glass-surface-hover)",
      surfaceStrong: "var(--glass-surface-strong)",
      border: "var(--glass-border)",
      borderTop: "var(--glass-border-top)",
    },
    vibrancy: {
      surface: "var(--vibrancy-surface)",
      border: "var(--vibrancy-border)",
    },
  },
  shadow: {},
  radius: {
    sm: "var(--radius-sm)",
    md: "var(--radius-md)",
    lg: "var(--radius-lg)",
    xl: "var(--radius-xl)",
    card: "var(--radius-card)",
    button: "var(--radius-button)",
    full: "var(--radius-full)",
  },
  wave: {
    intensity: "0.2",
    speedMult: "0.5",
    amplScale: "0.4",
    opacity: "0.25",
  },
} as const;

export type Tokens = typeof tokens;
export type ColorTokens = typeof tokens.color;
export type ShadowTokens = typeof tokens.shadow;
export type RadiusTokens = typeof tokens.radius;
